apiVersion: v1
kind: Secret
metadata:
  name: example-event-streaming
data:
  application.properties: |
    kafka.bootstrap.address=my.kafka.host.com:port
    messaging.broker.url=amqp://my-message-broker-host:port