apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1
  name: amq-streams
  namespace: event-streaming-kafka-cluster-dev
  selfLink: >-
    /apis/operators.coreos.com/v1alpha1/namespaces/event-streaming-kafka-cluster-dev/subscriptions/amq-streams
  uid: 4fd019bd-57bb-11ea-81fa-060792c44080
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amqstreams.v1.3.0
